#AUTHOR: Szymon Basiak
#STEPS todo:

#get the string
#split it to single letters
#each letter consist of 4 lines
#read single letter 
#in case of text = 'ko' start printing first line of k, and the o
#get next letter and do the loop for another letter
#break program if last character occurs...


def printing(letter)
case letter
when "a"
    @shape1 =  "  ###  "
    @shape2 =  " #   # "
    @shape3 =  " ##### "
    @shape4 =  " #   # "
    @shape5 =  " #   # "
  when "b"
    @shape1 =  " ####  "
    @shape2 =  " #   # "
    @shape3 =  " ####  "
    @shape4 =  " #   # "
    @shape5 =  " ####  "
  when "c"
    @shape1 =  "  ### "
    @shape2 =  " #    "
    @shape3 =  " #    "
    @shape4 =  " #    "
    @shape5 =  "  ### "
  when "d"
    @shape1 =  " ####  "
    @shape2 =  " #   # "
    @shape3 =  " #   # "
    @shape4 =  " #   # "
    @shape5 =  " ####  " 
   when "e"
    @shape1 =  " #### "
    @shape2 =  " #    "
    @shape3 =  " ##   "
    @shape4 =  " #    "
    @shape5 =  " #### "
  when "f"
    @shape1 =  " #### "
    @shape2 =  " #    "
    @shape3 =  " ##   "
    @shape4 =  " #    "
    @shape5 =  " #    "
  when "g"
    @shape1 =  "  ###  "
    @shape2 =  " #     "
    @shape3 =  " # ### "
    @shape4 =  " #   # "
    @shape5 =  "  ###  "
  when "h"
    @shape1 =  " #   # "
    @shape2 =  " #   # "
    @shape3 =  " ##### "
    @shape4 =  " #   # "
    @shape5 =  " #   # "
  when "i"
    @shape1 =  " ### "
    @shape2 =  "  #  "
    @shape3 =  "  #  "
    @shape4 =  "  #  "
    @shape5 =  " ### "
  when "j"
    @shape1 =  " ### "
    @shape2 =  "   # "
    @shape3 =  "   # "
    @shape4 =  "   # "
    @shape5 =  " ##  "
  when "k"
    @shape1 = " #  # "
    @shape2 = " # #  "
    @shape3 = " ##   "
    @shape4 = " # #  "
    @shape5 = " #  # "
  when "l"
    @shape1 = " #    "
    @shape2 = " #    "
    @shape3 = " #    "
    @shape4 = " #    "
    @shape5 = " #### "
  when "m"
    @shape1 =  " #    # "
    @shape2 =  " ##  ## "
    @shape3 =  " # ## # "
    @shape4 =  " #    # "
    @shape5 =  " #    # "
  when "n"
    @shape1 =  " #   # "
    @shape2 =  " ##  # "
    @shape3 =  " # # # "
    @shape4 =  " #  ## "
    @shape5 =  " #   # "
  when "o"
    @shape1 =  "  ###  "
    @shape2 =  " #   # "
    @shape3 =  " #   # "
    @shape4 =  " #   # "
    @shape5 =  "  ###  "
 when "p"
    @shape1 = " ###  "
    @shape2 = " #  # "
    @shape3 = " ###  "
    @shape4 = " #    "
    @shape5 = " #    "
 when "q"
    @shape1 =  "  ###  "
    @shape2 =  " #   # "
    @shape3 =  " #   # "
    @shape4 =  " #  #  "
    @shape5 =  "  ## # "
  when "r"
    @shape1 = " ###  "
    @shape2 = " #  # "
    @shape3 = " ###  "
    @shape4 = " # #  "
    @shape5 = " #  # "
  when "s"
    @shape1 = "  ### "
    @shape2 = " #    "
    @shape3 = "  ##  "
    @shape4 = "    # "
    @shape5 = " ###  "
  when "t"
    @shape1 =  " ##### "
    @shape2 =  "   #   "
    @shape3 =  "   #   "
    @shape4 =  "   #   "
    @shape5 =  "   #   "
  when "u"
    @shape1 =  " #   # "
    @shape2 =  " #   # "
    @shape3 =  " #   # "
    @shape4 =  " #   # "
    @shape5 =  "  ###  "
  when "v"
    @shape1 =  " #   # "
    @shape2 =  " #   # "
    @shape3 =  "  # #  "
    @shape4 =  "  # #  "
    @shape5 =  "   #   "
  when "w"
    @shape1 =  " #    # "
    @shape2 =  " #    # "
    @shape3 =  " # ## # "
    @shape4 =  " ##  ## "
    @shape5 =  " #    # "
  when "x"
    @shape1 =  " #   # "
    @shape2 =  "  # #  "
    @shape3 =  "   #   "
    @shape4 =  "  # #  "
    @shape5 =  " #   # "
  when "y"
    @shape1 =  " #   # "
    @shape2 =  "  # #  "
    @shape3 =  "   #   "
    @shape4 =  "   #   "
    @shape5 =  "   #   "
   when "z"
    @shape1 =  " ##### "
    @shape2 =  "    #  "
    @shape3 =  "   #   "
    @shape4 =  "  #    "
    @shape5 =  " ##### "
  when "!"
    @shape1 =  " ### "
    @shape2 =  " ### "
    @shape3 =  " ### "
    @shape4 =  "  #  "
    @shape5 =  " (#) "
  when " "
    @shape1 =  "     "
    @shape2 =  "     "
    @shape3 =  "     "
    @shape4 =  "     "
    @shape5 =  "     "
  when "?" || "," || "." || ";"
    @shape1 =  ""
    @shape2 =  ""
    @shape3 =  ""
    @shape4 =  ""
    @shape5 =  ""
  else
    @shape1 =  ""
    @shape2 =  ""
    @shape3 =  ""
    @shape4 =  ""
    @shape5 =  ""
end
end

puts "Widen your window and then \nput some short text here: "
text = gets.chomp


string = text.downcase.split("")

for counter in 1..5
string.each {
|x| printing(x)
variable = "@shape#{counter}"
print eval(variable)
sleep(0.05)
}
puts ""
end
